
package com.pifss.customerrestservice.pojos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateIndividualData", targetNamespace = "http://UpdateIndividualData")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateIndividualData {


    /**
     * 
     * @param updateCustomerProfileRequest
     * @return
     *     returns com.pifss.customerrestservice.pojos.UpdateCustomerProfileResponse
     */
    @WebMethod
    @WebResult(name = "updateCustomerProfileResponse", targetNamespace = "http://UpdateIndividualData", partName = "updateCustomerProfileResponse")
    public UpdateCustomerProfileResponse updateCustomerProfile(
        @WebParam(name = "updateCustomerProfileRequest", targetNamespace = "http://UpdateIndividualData", partName = "updateCustomerProfileRequest")
        UpdateCustomerProfileRequest updateCustomerProfileRequest);

    /**
     * 
     * @param getCustomerInfoRequest
     * @return
     *     returns com.pifss.customerrestservice.pojos.GetCustomerInfoResponse
     */
    @WebMethod
    @WebResult(name = "getCustomerInfoResponse", targetNamespace = "http://UpdateIndividualData", partName = "getCustomerInfoResponse")
    public GetCustomerInfoResponse getCustomerInfo(
        @WebParam(name = "getCustomerInfoRequest", targetNamespace = "http://UpdateIndividualData", partName = "getCustomerInfoRequest")
        GetCustomerInfoRequest getCustomerInfoRequest);

}
