
package com.pifss.customerrestservice.pojos;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UpdateIndividualDataService", targetNamespace = "http://UpdateIndividualData", wsdlLocation = "/wsdl/UpdateIndividualData.wsdl")
public class UpdateIndividualDataService
    extends Service
{

    private final static URL UPDATEINDIVIDUALDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATEINDIVIDUALDATASERVICE_EXCEPTION;
    private final static QName UPDATEINDIVIDUALDATASERVICE_QNAME = new QName("http://UpdateIndividualData", "UpdateIndividualDataService");

    static {
        UPDATEINDIVIDUALDATASERVICE_WSDL_LOCATION = com.pifss.customerrestservice.pojos.UpdateIndividualDataService.class.getResource("/wsdl/UpdateIndividualData.wsdl");
        WebServiceException e = null;
        if (UPDATEINDIVIDUALDATASERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/UpdateIndividualData.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        UPDATEINDIVIDUALDATASERVICE_EXCEPTION = e;
    }

    public UpdateIndividualDataService() {
        super(__getWsdlLocation(), UPDATEINDIVIDUALDATASERVICE_QNAME);
    }

    public UpdateIndividualDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATEINDIVIDUALDATASERVICE_QNAME, features);
    }

    public UpdateIndividualDataService(URL wsdlLocation) {
        super(wsdlLocation, UPDATEINDIVIDUALDATASERVICE_QNAME);
    }

    public UpdateIndividualDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATEINDIVIDUALDATASERVICE_QNAME, features);
    }

    public UpdateIndividualDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateIndividualDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateIndividualData
     */
    @WebEndpoint(name = "UpdateIndividualDataSoap11")
    public UpdateIndividualData getUpdateIndividualDataSoap11() {
        return super.getPort(new QName("http://UpdateIndividualData", "UpdateIndividualDataSoap11"), UpdateIndividualData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateIndividualData
     */
    @WebEndpoint(name = "UpdateIndividualDataSoap11")
    public UpdateIndividualData getUpdateIndividualDataSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://UpdateIndividualData", "UpdateIndividualDataSoap11"), UpdateIndividualData.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATEINDIVIDUALDATASERVICE_EXCEPTION!= null) {
            throw UPDATEINDIVIDUALDATASERVICE_EXCEPTION;
        }
        return UPDATEINDIVIDUALDATASERVICE_WSDL_LOCATION;
    }

}
